# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Set up build environment
        run: |
          cd gatsby-app-starter-rest-api
          sudo apt-get update
          curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
          sudo apt-get install -y nodejs
          sudo npm install -g yarn
          yarn
        #working-directory: gatsby-app-starter-rest-api

      # Runs a set of commands using the runners shell
      - name: Build code
        run: |
          cd gatsby-app-starter-rest-api
          wget -O src/components/Keys https://gist.githubusercontent.com/mayukhnair/db9c23cef1f50e9b64c12add18789b74/raw/5f28795a8b47b57f75fab458c03c28dcf6f5ff82/Greendubs%2520dummy%2520keyfile
          yarn gatsby build
        #working-directory: gatsby-app-starter-rest-api
